### PR TITLE
Tiny spacing change on number list

### PR DESCRIPTION
**Pull request by Jonty**
This just made me twitch.

### CODE REVIEW

**Comment by sammachin** [comment]
only thing here is that on a mobile browser the buttons end up across multiple lines and then the spaces make that go funky.
&nbsp; should be the solution i think but doesn't seem to play nice in my tests.
@MattGrayYes any ideas?

Generally our mobile UX is prettygood without doing anything special so I'm keen not to degrade that as I think people will use it quite a lot on phones once on site

**Comment by MattGrayYes** [comment]
So In my fork I've updated the spacing there anyway to remove the pipe characters, but the spaces become underlined, and `text-decoration-skip: spaces;` is basically unsupported, so ive left the underlined space
Screenshot 2024-05-08 at 13 28 56

**Comment by sammachin** [comment]
Using this issue as althouhg its different to the PR its the same thing we're talking about.

@MattGrayYes When viewed on mobile now something really funky happens to the table
IMG_EE98DD82911D-1

**Comment by sammachin** [comment]
The funkyness is a Safari thing, it looks even weirder in safari desktop
image
Equally Chrome on Android renders fine

**Comment by MattGrayYes** [comment]
I’ll have a look this afternoon

**Comment by sammachin** [comment]
Have resolved most of the browser issues in f3cec29ce28b347ae8587b6a5fc7a6f1186404b5 So it now looks "ok" in:
Safari iOS
Chrome Android
Safari Desktop 
Chrome Desktop
Firefox Desktop

Also changed the `Edit` button to be `Modify` so its 2 chars longer and wraps the same as the other 2.

Gonna close this PR and we can revist a better UI after EMF

**Pull request closed without merging**
